version: "3.7"
services:
  postgres:
    image: postgres:13-alpine
    restart: on-failure
    volumes:
      - abd_pgvolume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: adb_postgres
    networks:
      - abd_network
    ports:
      - 5432:5432
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  abd_pgvolume:
  
networks:
  abd_network:
    driver: bridge
 
